import { NextResponse } from 'next/server';
import { createClient } from '@/utils/supabase/server';
import { cookies } from 'next/headers';
import { GoogleGenerativeAI, SchemaType } from '@google/generative-ai';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { message, deviceId } = body;

    if (!message || !deviceId) {
      return NextResponse.json(
        { error: 'message and deviceId are required' },
        { status: 400 }
      );
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: 'เกิดข้อผิดพลาด: ไม่พบกุญแจ GEMINI_API_KEY ในระบบ' },
        { status: 500 }
      );
    }

    // Initialize Gemini AI
    const genAI = new GoogleGenerativeAI(apiKey);
    
    // Define a strict JSON schema for world-class reliable hardware commands
    const responseSchema = {
      type: SchemaType.OBJECT,
      properties: {
        reply: {
          type: SchemaType.STRING,
          description: "คำตอบของฟลอร่า ตอบกลับผู้ใช้เป็นภาษาไทย สั้นๆ น่ารักๆ ขี้อ้อน และใช้ Emoji ประกอบ",
        },
        device: {
          type: SchemaType.STRING,
          description: "ถ้าผู้ใช้ต้องการสั่งงานฮาร์ดแวร์ ให้ระบุอุปกรณ์ ('LED' สำหรับไฟ, 'PUMP' สำหรับรดน้ำ) ถ้าผู้ใช้แค่ชวนคุยให้ปล่อยเป็นสตริงว่าง ''",
        },
        command: {
          type: SchemaType.STRING,
          description: "คำสั่งที่ต้องการส่ง ('ON' เพื่อเปิด, 'OFF' เพื่อปิด) ถ้าผู้ใช้แค่ชวนคุยให้ปล่อยเป็นสตริงว่าง ''",
        }
      },
      required: ["reply", "device", "command"],
    };

    const model = genAI.getGenerativeModel({ 
      model: 'gemini-1.5-flash',
      generationConfig: {
        responseMimeType: "application/json",
        responseSchema: responseSchema,
      }
    });

    const prompt = `
คุณคือ "ฟลอร่า (Flaura)" ต้นไม้ AI ที่มีชีวิต ร่าเริง น่ารัก ขี้อ้อน และรักเจ้าของมาก 
คุณอาศัยอยู่ในกระถางอัจฉริยะ คุณสามารถคุยเรื่องทั่วไป หรือเรื่องความรู้สึกได้

ผู้ใช้พูดกับคุณว่า: "${message}"

ถ้าผู้ใช้สั่ง "เปิดไฟ", "รดน้ำ", "ปิดไฟ", หรือ "หิวน้ำ" ให้คุณระบุ device และ command ให้ถูกต้อง
ถ้าผู้ใช้แค่ชวนคุยเล่น ให้ device และ command เป็นสตริงว่าง ("")
ส่วน reply ให้ตอบกลับด้วยความน่ารักเสมอ
`;

    const result = await model.generateContent(prompt);
    const aiResponse = result.response.text();
    
    // Parse the strict JSON output
    let parsedResult;
    try {
      parsedResult = JSON.parse(aiResponse);
    } catch (e) {
      console.error("Failed to parse JSON from Gemini", e);
      throw new Error("Invalid AI output format");
    }

    const { reply, device, command } = parsedResult;

    // Connect to Supabase
    const cookieStore = await cookies();
    const supabase = createClient(cookieStore);

    let commandData = null;

    // If a hardware command was explicitly generated by AI, save it to Supabase
    if (device && command) {
      const { data, error } = await supabase
        .from('commands')
        .insert([
          {
            device_id: deviceId,
            device: device.toUpperCase(),
            command: command.toUpperCase(),
            value: null,
            status: 'PENDING'
          }
        ])
        .select()
        .single();

      if (error) {
        console.error('Error inserting command:', error);
        return NextResponse.json(
          { error: 'หนูติดต่อระบบรดน้ำไม่ได้ค่ะ แงงง (เกิดปัญหาการส่งคำสั่งไปฮาร์ดแวร์)' },
          { status: 500 }
        );
      }
      commandData = data;
    }

    return NextResponse.json({
      reply: reply.trim(),
      command: commandData,
      success: true
    });

  } catch (err: any) {
    console.error('Error in chat API:', err);
    return NextResponse.json(
      { error: err.message || 'หนูคิดไม่ออกค่ะ (ระบบ AI ขัดข้อง)' },
      { status: 500 }
    );
  }
}
